AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stores the Short and Long URL mappings.'

Resources:
  SimpleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ParticleUrlTable
      AttributeDefinitions:
        - AttributeName: ShortUrl
          AttributeType: S
        - AttributeName: LongUrl
          AttributeType: S
      KeySchema:
        - AttributeName: ShortUrl
          KeyType: HASH  # Partition Key
        - AttributeName: LongUrl
          KeyType: RANGE # Sort Key
      BillingMode: PROVISIONED # Required for the free throughput units
      ProvisionedThroughput:
        ReadCapacityUnits: 5 # 25 CUs is the maximum per account per region
        WriteCapacityUnits: 5 # 25 CUs is the maximum per account per region
      TimeToLiveSpecification:
        AttributeName: ExpiresAt
        Enabled: true