AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyUrlShortenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.cggreen.particleurl.Handler::handleRequest
      Runtime: java17
      CodeUri: . # Points to your built JAR
      Events:
        UrlEndpoint:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Architectures:
        - arm64